In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [7]:
dt_path=Path(
    "../data/raw/Beds-Timeseries-2010-11-onwards-Q1-2026-27.xlsx"
)
xls=pd.ExcelFile(dt_path)
print(xls.sheet_names)

['Open Overnight', 'Open Day Only']

In [8]:
beds=pd.read_excel(
    dt_path, sheet_name="Open Overnight"
)
print(beds.shape)
print(beds.columns.tolist())
beds.head()

(81, 23)
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,Title:,Average Daily Available and Occupied Beds Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Summary:,KH03 collects the number of available and occu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Period:,Q1 2010/11 to Q1 2026/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Source:,NHS England: data collection - KH03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
beds.iloc[5:15]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
5,NaN,Basis:,Provider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Published:,20th August 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Revised:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Status:,Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Contact:,england.bedsanddischarges@nhs.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,% Occupied,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Year,Period,Org Name,Total,General & Acute,Learning Disabilities,Maternity,Mental Illness,NaN,...,Maternity,Mental Illness,NaN,Total,General & Acute,Learning Disabilities,Maternity,Mental Illness,NaN,NaN
13,NaN,2010/11,Q1,England,144454.873626,110568.183516,2465.241758,7905.997802,23515.450549,NaN,...,4755.826593,20470.230769,NaN,0.84837,0.863086,0.768803,0.601547,0.870501,2010/11,Q1
14,NaN,2010/11,Q2,England,141477.344565,108348.798913,2237.293478,7962.023913,22929.228261,NaN,...,4878.85587,19878.282609,NaN,0.843232,0.85626,0.789478,0.612766,0.866941,NaN,Q2

In [10]:
beds=pd.read_excel(dt_path, sheet_name="Open Overnight", header=12)
print(beds.shape)
print(beds.columns.tolist())
beds.head()

(69, 23)
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Available', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Occupied', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', '% Occupied', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Available,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,% Occupied,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,Year,Period,Org Name,Total,General & Acute,Learning Disabilities,Maternity,Mental Illness,NaN,...,Maternity,Mental Illness,NaN,Total,General & Acute,Learning Disabilities,Maternity,Mental Illness,NaN,NaN
1,NaN,2010/11,Q1,England,144454.873626,110568.183516,2465.241758,7905.997802,23515.450549,NaN,...,4755.826593,20470.230769,NaN,0.84837,0.863086,0.768803,0.601547,0.870501,2010/11,Q1
2,NaN,2010/11,Q2,England,141477.344565,108348.798913,2237.293478,7962.023913,22929.228261,NaN,...,4878.85587,19878.282609,NaN,0.843232,0.85626,0.789478,0.612766,0.866941,NaN,Q2
3,NaN,2010/11,Q3,England,141629.632609,108023.228261,2087.858696,7778.11087,23740.434783,0.0,...,4738.468696,20399.554348,NaN,0.85785,0.877045,0.77478,0.609206,0.859275,NaN,Q3
4,NaN,2010/11,Q4,England,142319.227778,108889.851111,1973.755556,7848.254444,23607.366667,0.0,...,4738.112222,20455.566667,NaN,0.866215,0.886827,0.769548,0.603715,0.866491,NaN,Q4

In [11]:
raw_head=pd.read_excel(dt_path, sheet_name="Open Overnight", header=None, skiprows=11, nrows=2)
raw_head.T

      0           1
0   NaN         NaN
1   NaN         NaN
2   NaN         NaN
3   NaN         NaN
4   NaN   Available
5   NaN         NaN
6   NaN         NaN
7   NaN         NaN
8   NaN         NaN
9   NaN         NaN
10  NaN    Occupied
11  NaN         NaN
12  NaN         NaN
13  NaN         NaN
14  NaN         NaN
15  NaN         NaN
16  NaN  % Occupied
17  NaN         NaN
18  NaN         NaN
19  NaN         NaN
20  NaN         NaN

In [12]:
print(raw_head.iloc[0].tolist())
print(raw_head.iloc[1].tolist())

[np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), nan, np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), nan, np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), nan, np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan)]
[np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), 'Available', np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), 'Occupied', np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan), '% Occupied', np.float64(nan), np.float64(nan), np.float64(nan), np.float64(nan)]

In [14]:
beds=pd.read_excel(
    dt_path, sheet_name="Open Overnight",
    header=12
)
print(beds.iloc[0].tolist())

[np.float64(nan), 'Year', 'Period', 'Org Name', 'Total ', 'General & Acute', 'Learning Disabilities', 'Maternity', 'Mental Illness', np.float64(nan), 'Total ', 'General & Acute', 'Learning Disabilities', 'Maternity', 'Mental Illness', np.float64(nan), 'Total ', 'General & Acute', 'Learning Disabilities', 'Maternity', 'Mental Illness', nan, nan]

In [17]:
beds= pd.read_excel(
    dt_path, sheet_name="Open Overnight",
    header=12
)
beds.columns=["Unused_0", "Year", "Period", "Org_Name", "Available_Total", "Available_General_Acute", "Available_Learning_Disabilities", "Available_Maternity", "Available_Mental_Illness", "Unused_9", "Occupied_Total",
              "Occupied_General_Acute", "Occupied_Learning_Disabilities", "Occupied_Maternity", "Occupied_Mental_Illness", "Unused_15", "Occupancy_Total", "Occupancy_General_Acute", "Occupancy_Learning_Disabilities", "Occupancy_Maternity", "Occupancy_Mental_Illness", "Unused_21", "Unused_22"]
print(beds.shape)
print(beds.columns.tolist())
beds[["Year", "Period", "Org_Name", "Available_Total", "Occupied_Total", "Occupancy_Total"]].head()

(69, 23)
['Unused_0', 'Year', 'Period', 'Org_Name', 'Available_Total', 'Available_General_Acute', 'Available_Learning_Disabilities', 'Available_Maternity', 'Available_Mental_Illness', 'Unused_9', 'Occupied_Total', 'Occupied_General_Acute', 'Occupied_Learning_Disabilities', 'Occupied_Maternity', 'Occupied_Mental_Illness', 'Unused_15', 'Occupancy_Total', 'Occupancy_General_Acute', 'Occupancy_Learning_Disabilities', 'Occupancy_Maternity', 'Occupancy_Mental_Illness', 'Unused_21', 'Unused_22']

      Year  Period  Org_Name Available_Total Occupied_Total Occupancy_Total
0     Year  Period  Org Name          Total          Total           Total
1  2010/11      Q1   England   144454.873626  122551.226484         0.84837
2  2010/11      Q2   England   141477.344565  119298.215543        0.843232
3  2010/11      Q3   England   141629.632609  121496.936196         0.85785
4  2010/11      Q4   England   142319.227778  123278.987811        0.866215

In [18]:
beds=beds.drop(
    columns=["Unused_0", "Unused_9", "Unused_15", "Unused_21", "Unused_22"])
beds=beds[beds["Year"]!="Year"].copy()
beds=beds.reset_index(drop=True)
print(beds.shape)
print(beds.isna().sum())
beds.head()

(68, 18)
Year                               2
Period                             3
Org_Name                           3
Available_Total                    3
Available_General_Acute            3
Available_Learning_Disabilities    3
Available_Maternity                3
Available_Mental_Illness           3
Occupied_Total                     3
Occupied_General_Acute             3
Occupied_Learning_Disabilities     3
Occupied_Maternity                 3
Occupied_Mental_Illness            3
Occupancy_Total                    3
Occupancy_General_Acute            3
Occupancy_Learning_Disabilities    3
Occupancy_Maternity                3
Occupancy_Mental_Illness           3
dtype: int64

,Year,Period,Org_Name,Available_Total,Available_General_Acute,Available_Learning_Disabilities,Available_Maternity,Available_Mental_Illness,Occupied_Total,Occupied_General_Acute,Occupied_Learning_Disabilities,Occupied_Maternity,Occupied_Mental_Illness,Occupancy_Total,Occupancy_General_Acute,Occupancy_Learning_Disabilities,Occupancy_Maternity,Occupancy_Mental_Illness
0,2010/11,Q1,England,144454.873626,110568.183516,2465.241758,7905.997802,23515.450549,122551.226484,95429.883407,1895.285714,4755.826593,20470.230769,0.84837,0.863086,0.768803,0.601547,0.870501
1,2010/11,Q2,England,141477.344565,108348.798913,2237.293478,7962.023913,22929.228261,119298.215543,92774.783587,1766.293478,4878.85587,19878.282609,0.843232,0.85626,0.789478,0.612766,0.866941
2,2010/11,Q3,England,141629.632609,108023.228261,2087.858696,7778.11087,23740.434783,121496.936196,94741.282717,1617.630435,4738.468696,20399.554348,0.85785,0.877045,0.77478,0.609206,0.859275
3,2010/11,Q4,England,142319.227778,108889.851111,1973.755556,7848.254444,23607.366667,123278.987811,96566.408922,1518.9,4738.112222,20455.566667,0.866215,0.886827,0.769548,0.603715,0.866491
4,2011/12,Q1,England,137353.62967,104574.416484,1720.978022,7804.927473,23253.307692,116452.287473,90317.301209,1341.153846,4616.052198,20177.78022,0.847828,0.863665,0.779297,0.591428,0.867738

In [19]:
print(beds.shape)
print(beds.dtypes)
print(beds["Year"].iloc[0], beds["Period"].iloc[0])
print(beds["Year"].iloc[-1], beds["Period"].iloc[-1])
print(beds["Org_Name"].value_counts())
print(beds["Org_Name"].value_counts())
print(beds.isna().sum())

(68, 18)
Year                                  str
Period                                str
Org_Name                              str
Available_Total                    object
Available_General_Acute            object
Available_Learning_Disabilities    object
Available_Maternity                object
Available_Mental_Illness           object
Occupied_Total                     object
Occupied_General_Acute             object
Occupied_Learning_Disabilities     object
Occupied_Maternity                 object
Occupied_Mental_Illness            object
Occupancy_Total                    object
Occupancy_General_Acute            object
Occupancy_Learning_Disabilities    object
Occupancy_Maternity                object
Occupancy_Mental_Illness           object
dtype: object
2010/11 Q1
Notes:  nan
Org_Name
England    65
Name: count, dtype: int64
Org_Name
England    65
Name: count, dtype: int64
Year                               2
Period                             3
Org_Name                           3
Available_Total                    3
Available_General_Acute            3
Available_Learning_Disabilities    3
Available_Maternity                3
Available_Mental_Illness           3
Occupied_Total                     3
Occupied_General_Acute             3
Occupied_Learning_Disabilities     3
Occupied_Maternity                 3
Occupied_Mental_Illness            3
Occupancy_Total                    3
Occupancy_General_Acute            3
Occupancy_Learning_Disabilities    3
Occupancy_Maternity                3
Occupancy_Mental_Illness           3
dtype: int64

In [ ]:
#removing missing rows
beds=beds[beds["Org_Name"]=="England"].copy()
numeric_cols=beds.columns